### ISSUE TITLE
Plugin localization

### ISSUE THREAD

**Issue by yoren** [WPCollab/hello-emoji#55]
I could handle the localization for Traditional Chinese and Simplified Chinese, any other languages?

And we might need to discuss:
1) Which tool to edit the po files? I use POEdit.
2) Where we should put the language files? Since WordPress recommends developers not to includes them in plugins or themes recently. Create a new branch like assets should be a good solution.

**Comment by cfoellmann** [comment]
In the works: https://www.transifex.com/projects/p/hello-emoji/
