### ISSUE TITLE
Update jquery-textcomplete

### ISSUE THREAD

**Issue by cfoellmann** [WPCollab/hello-emoji#89]
https://github.com/yuku-t/jquery-textcomplete is now on 0.1.3 - update?

**Comment by cfoellmann** [comment]
It is already at 0.3.6 - I will wait for bower to implement this https://github.com/bower/bower/issues/927 and integrate a more current version via bower

**Comment by yoren** [comment]
I'll try 0.3.6 to check if the bug had gone.

**Comment by yoren** [comment]
To update jquery-texcomplete to the latest version, we need to update our js / css accordingly, or the autocomplete will be kind of broken. I'll take a look into how to implement it.
