### ISSUE TITLE
Retire with WP 4.2

### ISSUE THREAD

**Issue by cfoellmann** [WPCollab/hello-emoji#96]
Hi guys,
I am all for retiring stuff if it is not needed or working anymore. Maybe we should look into the new WP 4.2 feature and if it is at least as good as out plugin retire hello-emoji.
As much as I like the wp.org repo I hate the dead weight and trash in it. I suspect that 70-80% is just crap.

What do you guys think?

**Comment by yoren** [comment]
I haven't test 4.2 but I will this weekend. If hello emoji can be replaced with new features in core, I agree that it's a good time to retire this project. Let me get back to you a couple of days later.

**Comment by slobodan** [comment]
I agree with @cfoellmann. Now that core does important things like this :) best to retire the plugin from wp.org repo. No issues with leaving it here at GitHub though.

**Comment by cfoellmann** [comment]
We are almost at WP 4.3 now.
What do you think about retirement? Let's do it now.

**Comment by yoren** [comment]
Let's retire this project. It's my pleasure to work with you guys!

**Comment by slobodan** [comment]
Same here, @yoren! Yes, time for retirement.

**Comment by cfoellmann** [comment]
Is there a way to disable the plugin on wordpress.org? I couldnt find any option for that in the admin area https://wordpress.org/plugins/hello-emoji/admin/

**Comment by yoren** [comment]
Can't find a way either. Maybe we should send a request to do so? (But not sure whom to send)

**Comment by cfoellmann** [comment]
plugins at wordpress.org maybe

**Comment by yoren** [comment]
Yep looks like it is (http://wordpress.stackexchange.com/questions/423/delete-wordpress-plugin-repository). Would @cfoellmann like to send this email? Or I could do.

**Comment by cfoellmann** [comment]
Would be great if you could do it!

**Comment by yoren** [comment]
Sure. I'll do it next week and report to you guys!

**Comment by yoren** [comment]
Email just sent. I'll keep you posted. ;)

**Comment by yoren** [comment]
The reply from plugins team is as the following:

==================

Per your request, the plugin page has been closed. Please note it will remain in the SVN repository, but it will no longer be downloadable. If you wish to remove the code entirely, you may use SVN to do so on your own.

Also you'll still see your plugin page if you're logged in. Don't worry, no one but you and the site admins can see it.

Please note: By asking for your plugin to be removed you are asking for a permanent change. This is not meant to be a stop-gap so you can work on a new version, it's intended as a final closure for code that you will no longer work on. Should you return and ask us to reopen it, be prepared to justify your initial request and explain in detail the reasons you would like the repository back.

==================

So now I'm closing this issue. Cheers!

**Comment by cfoellmann** [comment]
Thanks!
